schema = 3

[mod]
  [mod."github.com/GeertJohan/yubigo"]
    version = "v0.0.0-20190917122436-175bc097e60e"
    hash = "sha256-Lb6prdQWQI2yH3JXwZwehmnypGCEJKt2EqQJDQLYFkk="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/boombuler/barcode"]
    version = "v1.0.1"
    hash = "sha256-mdptFdhAM2+xm8RBOuViCi/l5qtoIO3fdT+rPuC7nmw="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/glauth/glauth/v2"]
    version = "v2.3.2"
    hash = "sha256-JR57u9Ie9G0PC1h/y+74TgU5JqJwya/4aIPu/SswVvI="
    replaced = "github.com/leroycep/glauth/v2"
  [mod."github.com/glauth/ldap"]
    version = "v0.0.0-20231210225823-b9bf4d1baf6e"
    hash = "sha256-lBSKOOgcs/jPTtkq6GnkDY3oesRiMsK7LRBfBcknJVY="
  [mod."github.com/go-asn1-ber/asn1-ber"]
    version = "v1.5.4"
    hash = "sha256-9a0DMr92zbvAq5Yi3mUVpWB5yLniLhNqaot4ykC8rD4="
  [mod."github.com/go-logr/logr"]
    version = "v1.3.0"
    hash = "sha256-N8JYtQlwpLWTaCczfhfA/YmHExko0ObPMYVGw8JwbSw="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.19"
    hash = "sha256-wYQqGxeqV3Elkmn26Md8mKZ/viw598R4Ych3vtt72YE="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.15"
    hash = "sha256-fSrs2sdBKFTAiffBHNnAkN8kDTqiXgm4HNqzJAOF1RM="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.4"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/pquerna/otp"]
    version = "v1.4.0"
    hash = "sha256-Eom/s+uV9o7JH2xx9ugaO1rdotaEAadsmWCZ7UohetI="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.17.0"
    hash = "sha256-FIIzCuNqHdVzpbyH7yAp7Tcu+1tPxEMS5g6KfsGQBGE="
  [mod."github.com/prometheus/client_model"]
    version = "v0.5.0"
    hash = "sha256-/sXlngf8AoEIeLIiaLg6Y7uYPVq7tI0qnLt0mUyKid4="
  [mod."github.com/prometheus/common"]
    version = "v0.44.0"
    hash = "sha256-8n3gSWKDSJtGfOQgxsiCGyTnUjb5hvSxJi/hPcrE5Oo="
  [mod."github.com/prometheus/procfs"]
    version = "v0.11.1"
    hash = "sha256-yphZ7NZtYC/tb0HVag2T58SuN64Ial9sBo/TdCEQx6Q="
  [mod."github.com/rickb777/date"]
    version = "v1.12.4"
    hash = "sha256-l+AowQj6N/M1ZpgPTOvNSgUkTcQkNJ6ecUDAj7SBp9I="
  [mod."github.com/rickb777/plural"]
    version = "v1.2.0"
    hash = "sha256-I3q/GVCi/nm2+Bea89AoPYVas2GdOkkKWn8JTf9QIoA="
  [mod."github.com/rs/zerolog"]
    version = "v1.31.0"
    hash = "sha256-OF4VM+Rv6M5EAaUVD2nOzcbZLQ4b7OAMteyyTqIoU0M="
  [mod."github.com/uptrace/opentelemetry-go-extra/otelsql"]
    version = "v0.2.3"
    hash = "sha256-8m6TSB75H9PMonvWU7jYp0Cn9cABOVbkgBHRyTrMe4Q="
  [mod."github.com/yaegashi/msgraph.go"]
    version = "v0.1.4"
    hash = "sha256-bK1ZPJVX3N6nTCYMqVYrwojd399HSPF48td6IlmAppE="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.21.0"
    hash = "sha256-MWC1fp41z3w3Y1wlECY12Q7sLeU4PRACZEesWTmDD9E="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.21.0"
    hash = "sha256-UH5fN59juP5GRiTpr5VUv4JGAE2o47LOyR7Ic6Yl/v4="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.21.0"
    hash = "sha256-vjZsOaQCgTjz6WYim0YZHLnB/PC3CvTSpS97qkL2vz8="
  [mod."golang.org/x/crypto"]
    version = "v0.17.0"
    hash = "sha256-/vzBaeD/Ymyc7cpjBvSfJfuZ57zWa9LOaZM7b33eIx0="
  [mod."golang.org/x/sys"]
    version = "v0.15.0"
    hash = "sha256-n7TlABF6179RzGq3gctPDKDPRtDfnwPdjNCMm8ps2KY="
  [mod."google.golang.org/protobuf"]
    version = "v1.31.0"
    hash = "sha256-UdIk+xRaMfdhVICvKRk1THe3R1VU+lWD8hqoW/y8jT0="
